name: Kero RDP

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'Please paste the URL of the webpage or file you want to download:'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        
    - name: Install OpenVPN
      run: choco install openvpn -y
      
    - name: Download Portmap Configuration
      run: |
        $inputUrl = "${{ github.event.inputs.portmap_config_url }}"
        $fileName = [System.IO.Path]::GetFileName($inputUrl)
        $newUrl = "https://raw.githubusercontent.com/kokokero1/windows/main/koko/$fileName"
        Invoke-WebRequest -Uri $newUrl -OutFile "C:\portmap.ovpn"
        
    - name: Enable Remote Desktop
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      
    - name: Set RDP Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Open Local User KeroAdmin
      run: |
        if (-not (Get-LocalUser -Name "KeroAdmin" -ErrorAction SilentlyContinue)) {
          New-LocalUser -Name "KeroAdmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force) -FullName "Kero Admin" -Description "Local user KeroAdmin"
          Add-LocalGroupMember -Group "Administrators" -Member "KeroAdmin"
        } else {
          Write-Output "User KeroAdmin already exists."
        }

    - name:  RDP Port 4000
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "PortNumber" -Value 4000
        New-NetFirewallRule -DisplayName "RDP Port 4000" -Direction Inbound -Protocol TCP -LocalPort 4000 -Action Allow

    - name: Restart Remote Desktop Service
      run: |
        Restart-Service -Name "TermService" -Force

    - name: The User Name and Password
      run: |
        Write-Output "User Name: KeroAdmin"
        Write-Output "Password: P@ssw0rd!"


    - name: Start 
      run: |
        Start-Process -NoNewWindow -FilePath "C:\Program Files\OpenVPN\bin\openvpn.exe" -ArgumentList "--config C:\portmap.ovpn" -Wait
        
    - name: Enable Terminal Services
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
